server:
  port: 8082
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/blog?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:postgresql://arjuna.db.elephantsql.com/umpunueu
    #username: root
    #password: Maple7574@
    username: umpunueu
    password: LjGBom9FphvO7rb3aUgAiuz69AA9W4np
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver
  jpa:
    database: mysql
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    